blank_issues_enabled: false
contact_links:
  - name: 📧 Контактная информация проекта
    url: https://github.com/meteo/esp32cam_project
    about: Посетите репозиторий проекта для получения дополнительной информации.